### ISSUE TITLE
serialize giving an object

### ISSUE THREAD

**Issue by sylvainlb** [rdf-ext/rdf-serializer-jsonld#1]
I have an object a such that:
```
a.toString()
"<./> <http://schema.org/parent> <localhost:8000/project/ldpcontainer/5> .
<./> <http://schema.org/title> "youpi" ."
```
When I serialize it, I get an object:
```
new rdf.JsonLdSerializer().serialize(a)
[Object]
```
So that the add function of rdf-ext sends `"[Object]"` to the server, which, obviously, it doesn't understand.

Am I doing something wrong in the way I call the serializer? I guess a serializer is supposed to give me a string.
My guess for a fix would be to stringify the result if it's not a string, but it might not be a smart move as I don't understand what's going on here.

**Comment by bergos** [comment]
The new serializer interface uses Promises by default. What you get is a Promise object. Here old vs. new:

```
// old
var serialized = rdf.JsonLdSerializer.serialize(graph);


// new
JsonLdSerializer.serialize(graph).then(function (serialized) {

});
```

It's not possible to implement all serializers with sync code, so a common interface must be asnyc.

Also have in mind, that in the JsonLd case serialized is still an object, but a plain object, that can be converted to string. That's by design. Serializers can output any format, because it's also serialization dependent. A binary format shouldn't be written to a string and there is even the possibility to return complex objects. For example a ReactRDFaSerializer could return a React component.

**Comment by sylvainlb** [comment]
Thanks for your answer!
Actually, I am using promises. I just wrote it like that here for simplification. Sorry if that was confusing.

So I'm wondering if there isn't an issue with rdf-ext then, because on add, it sends directly to the server the result of the serialization. With the default turtle serializer that's befine because it's a string, but when you set json-ld as default serializer, it sends "[Object]" to the server.

**Comment by bergos** [comment]
You are right, I tried it last night. With all the mock objects in the LdpStore, real serializers never get tested. But I think I have a nice solution:

- add an option for the serializer to output strings (should be the same property for all serializers!)
- create an instance with that flag set to true in the rdf-mime-type-utils
- add at least a small single triple test case in the LdpStore

I'm not sure about the property name. toString, outputString? Is there any package we can have a look at?

@nicola What would you propose?

**Comment by nicola** [comment]
Tell me if i am getting this wrong.

it should all work in this way:

```
JsonLdSerializer.serialize(graph).then(function (serialized) {
    // serialized is a string
});
```

can't check now, but what does it return now? a JSON obj?

**Comment by sylvainlb** [comment]
Yes exactly, and turned into a string it gives '[Object]'

**Comment by bergos** [comment]
[HDT](http://www.rdfhdt.org/hdt-binary-format/) is a better use case where string output doesn't make sense. But it's the same for JSON-LD. If you want to do further processing of the output with the JSON-LD library, string output would require JSON.stringify() -> JSON.parse(). That's why I would propose the following solution:

```
// with toString option
(new JsonLdSerializer({toString: true})).serialize(graph).then(function (serialized) {
  // now it's a string
}
```

**Comment by sylvainlb** [comment]
Hello, I'm coming back here because I'm facing the issue again. I don't remember if and how I solved the issue last time.
Would you by any chance have come up with a fix to that issue?

I've tried with the option you suggest, but I'm getting an error: `"JSON parse error - No JSON object could be decoded"`. I don't really understand where the tostring option is supposed to be passed.

**Comment by sylvainlb** [comment]
I've been looking into it for a fix, but I'm still using version 1.2 of rdf-ext, so I need to migrate before I can do anything.
The thing is my use case involves a LDP store and I couldn't find any reference to using a store in the documentation. Is there somewhere an example on how to create a LDP store with rdf ext?

**Comment by bergos** [comment]
There is a [outputString](https://github.com/rdf-ext/rdf-serializer-jsonld/blob/master/index.js#L79) option in the latest version.

[SimpleRDF](https://github.com/simplerdf/simplerdf/blob/master/index.js#L10) creates one and does some basic processing: `[.graph](https://github.com/simplerdf/simplerdf/blob/master/index.js#L28)` `[.add](https://github.com/simplerdf/simplerdf/blob/master/index.js#L45)`

The [ldp module](https://github.com/bergos/ldp/blob/master/ldp.js) also uses a store, just the interface, not specific the LDPStore.

What exactly are your looking for?

**Comment by sylvainlb** [comment]
Thanks. Then I guess I need to figure out how to migrate to 1.3 to solve all of my issues.
Actually I discovered SimpleRDF a few days ago, and it might be exactly the same thing as [the framework we're making](https://github.com/Open-Initiative/LDP-framework). If it's the case then we'll probably drop this component work to join efforts with you on SimpleRDF. I'll have a look in a next few days.

As for the server, we're mostly using Django and [wordpress](https://github.com/Open-Initiative/wpldp) but it's a good thing to know there's a node component.

**Comment by bergos** [comment]
Yes, that would be cool, if we could join efforts. SimpleRDF could be used for the objects, but the rendering and form handling stuff is out of scope. I think the best would be to build your framework on top of SimpleRDF. The LDP handling could be implemented as plugin. We plan to [restructure the packages](https://github.com/simplerdf/simplerdf/issues/53) a little bit. A `simplerdf-ldp` could implement the container stuff.

**Comment by sylvainlb** [comment]
Actually we were planning to drop the rendering and form handling as we're moving to using [web components](https://github.com/HappyDev-team/LDP-Components). So SimpleRDF would probably do the job by itself.

What do you mean by "the container stuff"? Like create a container, delete a resource?

**Comment by bergos** [comment]
Cool. I also started using Web Components in the [Dark Horse UI](https://github.com/bergos/dark-horse-ui) with SimpleRDF. I'm using Polymer. I have to figure out what's the best way to bundle the package. The build step isn't very nice right now, but it's working :-)

Yes, creating containers and removing resources.

**Comment by sylvainlb** [comment]
Ok. I'll take a deeper dive into the code and I'll try to make a plugin.
